"use client";

import { useState, useEffect } from "react";
import { useAuth, useUser, UserButton } from "@clerk/nextjs";
import { useRouter } from "next/navigation";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";

const DELIVERY_TIMES = [
  "06:00", "07:00", "08:00", "09:00", "10:00",
  "12:00", "14:00", "16:00", "18:00", "20:00",
];

const STARTER_PROFILES: { label: string; text: string }[] = [
  {
    label: "Tech",
    text: "I follow software engineering and AI closely — new developer tools, LLM releases and research, open-source projects gaining traction, systems programming, and major launches from companies like OpenAI, Anthropic, and Google DeepMind.",
  },
  {
    label: "Gaming",
    text: "I follow the games industry — new releases and reviews, indie game development, game engine news (Unreal, Unity, Godot), esports results, and business news about studios and publishers.",
  },
  {
    label: "Music",
    text: "I follow music — new album releases and reviews across genres, music production tools and techniques, the streaming industry, vinyl culture, and stories about how artists make a living today.",
  },
  {
    label: "Finance",
    text: "I follow markets and finance — macro trends, central bank policy, notable startup funding rounds and IPOs, fintech products, and long-form analysis on investing and the global economy.",
  },
  {
    label: "Literature",
    text: "I follow books and writing — notable new fiction and non-fiction releases, literary prize news, essays on the craft of writing, the publishing industry, and thoughtful long-form criticism.",
  },
];

function today() {
  return new Date().toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  });
}

export default function OnboardingPage() {
  const { getToken } = useAuth();
  const { user } = useUser();
  const router = useRouter();

  const [interests, setInterests] = useState("");
  const [deliveryTime, setDeliveryTime] = useState("08:00");
  const [timezone, setTimezone] = useState("UTC");
  const [emailDigest, setEmailDigest] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [prefilling, setPrefilling] = useState(true);

  const userEmail = user?.primaryEmailAddress?.emailAddress ?? "";

  const apiUrl = process.env.NEXT_PUBLIC_API_URL;

  useEffect(() => {
    setTimezone(Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC");

    async function loadExisting() {
      try {
        const token = await getToken();
        const res = await fetch(`${apiUrl}/api/profile`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (res.ok) {
          const data = await res.json();
          setInterests(data.interests);
          setDeliveryTime(data.delivery_time);
          setTimezone(data.timezone);
          setEmailDigest(Boolean(data.email_digest));
        }
      } catch {
        // no existing profile — fine, start blank
      } finally {
        setPrefilling(false);
      }
    }

    loadExisting();
  }, [getToken, apiUrl]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!interests.trim()) return;

    setLoading(true);
    setError("");

    try {
      const token = await getToken();
      const res = await fetch(`${apiUrl}/api/profile`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          interests,
          delivery_time: deliveryTime,
          timezone,
          email_digest: emailDigest,
          email: userEmail || null,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        setError(data.detail || "Something went wrong. Try again.");
        return;
      }

      // Kick off the pipeline — the backend ignores this if one is already
      // running for this user, so it is safe to fire on every save.
      try {
        await fetch(`${apiUrl}/api/pipeline/run`, {
          method: "POST",
          headers: { Authorization: `Bearer ${token}` },
        });
      } catch {
        // digest will still be generated by the daily cron
      }

      router.push("/dashboard?generating=1");
    } catch {
      setError("Could not reach the server. Check your connection.");
    } finally {
      setLoading(false);
    }
  }

  const charsLeft = 2000 - interests.length;

  return (
    <div className="min-h-screen bg-vellum font-body">
      <div className="max-w-2xl mx-auto px-6 py-10">

        {/* Masthead */}
        <header className="flex items-baseline justify-between">
          <Link
            href="/dashboard"
            className="font-display font-black text-3xl tracking-tight text-ink hover:text-walnut transition-colors"
          >
            PULSE
          </Link>
          <div className="flex items-center gap-4">
            <span className="font-mono text-xs text-pencil">{today()}</span>
            <UserButton afterSignOutUrl="/" />
          </div>
        </header>

        {/* Double rule */}
        <div className="mt-3 border-t border-pencil" />
        <div className="mt-[3px] border-t border-pencil mb-6" />

        <SiteNav current="profile" />

        {/* Header */}
        <div className="mb-6">
          <span className="tag text-walnut border-walnut">Profile setup</span>
        </div>

        <h1 className="font-display font-bold text-2xl text-ink tracking-tight mb-2">
          What are you following right now?
        </h1>
        <p className="text-pencil text-sm mb-1">
          Write in plain English — topics, domains, questions, or projects you want
          Pulse to track each day.
        </p>
        <p className="margin-note mb-10">
          — The more specific you are, the sharper your digest will be.
        </p>

        {prefilling ? (
          <p className="font-mono text-xs text-pencil">Loading...</p>
        ) : (
          <form onSubmit={handleSubmit}>

            {/* Starter profiles */}
            <div className="mb-6">
              <p className="font-mono text-xs text-pencil uppercase tracking-widest mb-2">
                Start from a template
              </p>
              <div className="flex flex-wrap gap-2">
                {STARTER_PROFILES.map((p) => (
                  <button
                    key={p.label}
                    type="button"
                    onClick={() => setInterests(p.text)}
                    className="tag text-walnut border-walnut hover:bg-walnut hover:text-vellum transition-colors cursor-pointer"
                  >
                    {p.label}
                  </button>
                ))}
              </div>
              <p className="margin-note mt-2">
                — Templates are just a starting point. Edit the text to make it yours.
              </p>
            </div>

            {/* Interests */}
            <div className="mb-8">
              <label className="block font-mono text-xs text-pencil uppercase tracking-widest mb-2">
                Your interests
              </label>
              <textarea
                value={interests}
                onChange={(e) => setInterests(e.target.value.slice(0, 2000))}
                rows={8}
                placeholder="e.g. I am a software engineer interested in LLM tooling, systems programming in Rust, Y Combinator funding rounds, and multi-agent AI research papers..."
                className="w-full bg-vellum border border-ink text-ink font-body text-sm leading-reading p-4 resize-none focus:outline-none focus:border-walnut placeholder:text-pencil"
              />
              <div className="flex justify-end mt-1">
                <span
                  className={`font-mono text-xs ${
                    charsLeft < 100 ? "text-wax" : "text-pencil"
                  }`}
                >
                  {charsLeft} characters remaining
                </span>
              </div>
            </div>

            {/* Delivery time */}
            <div className="mb-6">
              <label className="block font-mono text-xs text-pencil uppercase tracking-widest mb-2">
                Delivery time
              </label>
              <div className="relative inline-block">
                <select
                  value={deliveryTime}
                  onChange={(e) => setDeliveryTime(e.target.value)}
                  className="bg-vellum border border-ink text-ink font-mono text-sm py-2 pl-3 pr-10 focus:outline-none focus:border-walnut appearance-none cursor-pointer"
                >
                  {DELIVERY_TIMES.map((t) => (
                    <option key={t} value={t}>{t}</option>
                  ))}
                </select>
                <span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 font-mono text-xs text-pencil">
                  ▾
                </span>
              </div>
              <p className="font-mono text-xs text-pencil mt-2">
                Your digest will be compiled and ready at this time each morning.
              </p>
            </div>

            {/* Timezone */}
            <div className="mb-10">
              <label className="block font-mono text-xs text-pencil uppercase tracking-widest mb-2">
                Timezone
              </label>
              <input
                type="text"
                value={timezone}
                onChange={(e) => setTimezone(e.target.value)}
                className="bg-vellum border border-ink text-ink font-mono text-sm py-2 px-3 w-64 focus:outline-none focus:border-walnut"
              />
              <p className="font-mono text-xs text-pencil mt-2">
                IANA format — e.g. America/New_York, Europe/London, Asia/Karachi
              </p>
            </div>

            {/* Email delivery */}
            <div className="mb-10">
              <p className="font-mono text-xs text-pencil uppercase tracking-widest mb-2">
                Email delivery
              </p>
              <label className="flex items-start gap-3 cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={emailDigest}
                  onChange={(e) => setEmailDigest(e.target.checked)}
                  className="appearance-none w-4 h-4 mt-[3px] border border-ink bg-vellum checked:bg-walnut checked:border-walnut cursor-pointer shrink-0"
                />
                <span className="text-ink text-sm leading-reading">
                  Email me my digest each morning
                  {userEmail && (
                    <span className="block font-mono text-xs text-pencil mt-1">
                      → {userEmail}
                    </span>
                  )}
                </span>
              </label>
              <p className="margin-note mt-2">
                — Your digest always appears here on the dashboard either way.
              </p>
            </div>

            {/* Error */}
            {error && (
              <p className="font-mono text-xs text-wax mb-6">{error}</p>
            )}

            {/* Submit */}
            <div className="flex items-center gap-6">
              <button
                type="submit"
                disabled={loading || !interests.trim()}
                className="btn-wax disabled:opacity-40 disabled:cursor-not-allowed"
              >
                {loading ? "Saving..." : "Start my digest"}
              </button>
              <span className="font-mono text-xs text-pencil">
                You can edit this any time from settings.
              </span>
            </div>

          </form>
        )}

        {/* Footer rule */}
        <div className="entry-rule mt-16 pt-6">
          <p className="font-mono text-xs text-pencil">
            Ten entries. Every morning. Nothing more.
          </p>
        </div>

      </div>
    </div>
  );
}
